// app.js
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { connectToServer } = require('./db/connection');
const routes = require('./routes');
const swaggerUi = require('swagger-ui-express');
const bodyParser = require('body-parser');
const passport = require('passport');
const session = require('express-session');
require('./auth/passportConfig'); // <-- Important

const app = express();
const PORT = process.env.PORT || 3003;

// Load Swagger docs (generated by swagger.js)
let swaggerDocument;
try {
  swaggerDocument = require('./swagger-output.json');
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
  console.log('✅ Swagger UI route loaded at /api-docs');
} catch (e) {
  console.warn('⚠️ Swagger file not found. Run "npm run swagger" first.');
}

app.use(cors());
app.use(express.json());

// Main routes
app.use('/', routes);

// 404 fallback
app.use((req, res) => {
  res.status(404).json({ error: 'Route not found' });
});

// Error handling
app.use((err, req, res, next) => {
  console.error('❌ Server Error:', err);
  res.status(err.status || 500).json({ error: err.message || 'Server error' });
});

// Connect to DB then start
connectToServer((err) => {
  if (err) {
    console.error('❌ DB connection failed:', err);
    process.exit(1);
  } else {
    app.listen(PORT, () =>
      console.log(`🚀 Server running on http://localhost:${PORT}`)
    );
  }
});


// Middleware
app.use(bodyParser.json());

// Set up session
app.use(
  session({
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false
  })
);

// Initialize passport
app.use(passport.initialize());
app.use(passport.session());

// Routes
app.use('/auth', require('./routes/auth')); // <-- Add this line
app.use('/', require('./routes')); // Your existing routes

// Error handling for invalid routes
app.use((req, res) => res.status(404).json({ error: 'Route not found' }));

module.exports = app;